### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by karur4n** [marzocchi/zsh-notify#13]
I can receive correct notify from Notification Center. but, print syntax error.

```
$ sleep 31
$ 85:88: syntax error: Expected “,” but found property. (-2741)
```

in my.zsh
```
source ~/dotfiles/zsh/terminal-notifier
export NOTIFY_COMMAND_COMPLETE_TIMEOUT=10
```

## System
iTerm 2 - 2.0.0.20141103
zsh-notify(branch: next-iterm) - 7f469ada8e29994b0491a29de16440059d893ceb

**Comment by marzocchi** [comment]
hi @karur4n,

the next-iterm branch is intended to be used with iTerm's **nightlies** that have a different AppleScript dictionary, can you try switching to master?

**Comment by karur4n** [comment]
Try switching, but as before, print syntax error.

Maybe my setting is conflicting this software.

**Comment by marzocchi** [comment]
Do you by chance have multiple versions of iTerms installed?

**Comment by karur4n** [comment]
No, I am using only v 2.0.0.20141103.

**Comment by marzocchi** [comment]
I just tested with the same version you are using ([the beta, right?][beta]), and when using the master branch, no AppleScript syntax error is reported.

At this point my suggestion would be to:

1. Throw iTerm in the trash, then emptyting it;
2. Run a simple script targeting iTerm, such as this `tell app "iterm" to activate` in order to get the "Choose Application" prompt and then cancel the prompt;
3. Reinstall iTerm, making sure that you are using the `next-iterm` branch if you chose to download a nightly, or `master` for other versions;

[beta]: https://iterm2.com/downloads.html
