### ISSUE TITLE
Display duration of notifcation window

### ISSUE THREAD

**Issue by te-gpm** [marzocchi/zsh-notify#17]
Love the plugin, works like a charm. Thanks for your work!

One little thing comes to mind that would make it even more useful: Would it be possible to designate a value for how long the notifcation window should be displayed? Or have it stay visible until it is clicked?

The current duration is rather short so there is a good chance I might just miss it when the task has been running for half an hour and I'm in a meeting or something.

**Comment by marzocchi** [comment]
Thank you!

Are you talking about notifications on OS X? Because I'm under the impression that this behaviour is built into OS X's Notification Center, eg.: if your Mac is idle, notifications should be visibile until you come back. I haven't really checked if this is true for my plugin, but I usually have notifications waiting for me on the Mac at home when I come back from work.

Anyway, there's no parameter for this in [terminal-notifier](https://github.com/alloy/terminal-notifier).

**Comment by te-gpm** [comment]
Thanks for your reply. 
Yes, I am talking about the notifaction on OSX. They keep disappearing on my machine, but maybe I just need to dig into the settings if it is the standard notification application. :)
Couldn't find a corresponding setting in terminal-notifier as well, unfortunatelly.
