### ISSUE TITLE
Confusion about customization 

### ISSUE THREAD

**Issue by mhartington** [marzocchi/zsh-notify#33]
Hi there! So this is an amazing plugin, and so far has been working great out of the box. When I try to customize the notification though, it does not seem to be working.

Using these settings (pulled from the readme) I'm not able to see custom success and failure titles/images.

https://github.com/mhartington/dotfiles/blob/master/zshrc#L39-L43

```
zstyle ':notify:*' notifier /usr/local/bin/terminal-notifier
zstyle ':notify:*' error-icon "https://media3.giphy.com/media/10ECejNtM1GyRy/200_s.gif"
zstyle ':notify:*' error-title "wow such #fail"
zstyle ':notify:*' success-icon "https://s-media-cache-ak0.pinimg.com/564x/b5/5a/18/b55a1805f5650495a74202279036ecd2.jpg"
zstyle ':notify:*' success-title "very #success. wow"
```

This is what I end up seeing.

![screen shot 2016-08-01 at 8 12 46 pm](https://cloud.githubusercontent.com/assets/2835826/17312910/d599d740-5824-11e6-9f16-a4f71c172967.png)

Not sure if this has to do with me using antigen or how I'm setting the notifier. Any ideas?

**Comment by marzocchi** [comment]
hello @mhartington and thank you!

the first line where you are setting `notifier` causes `terminal-notifier` to be invoked directly without the icon and title settings.

but you actually not need it: the `notifier` setting is useful only if you want to use a custom script, maybe because you want to use a different “output” than Notification Center.

**Comment by mhartington** [comment]
Such wow!

Thanks for the heads up, I was not aware of that! 
cheers!

**Comment by marzocchi** [comment]
@mhartington yeah i should probably make it more clear in the readme!
