### ISSUE TITLE
Use relevant icon for error notifications on Gnome Linux

### ISSUE THREAD

**Issue by adambro** [marzocchi/zsh-notify#52]
First of all: great ZSH extension. Could you use different icon for error, please? Currenty on Gnome 3.24 on Antergos it always displays green icon like that
![fail_green_icon](https://user-images.githubusercontent.com/649233/28174767-bb552a7c-67f2-11e7-863c-1cfe0422dd26.png)

It seems that the `$icon` variable is not set, at least for Linux. For errors you could use `dialog-error` or `dialog-warning` icons from standard:
https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

I could try to contribute patch, but I don't have MacOSX to test it. Frankly I don't even know if it has the same issue or not.

**Comment by marzocchi** [comment]
Hello!

I'm not choosing a default icon, but you can set your prefence for error and success in your .zshrc. See the README.md or [this](https://gist.github.com/marzocchi/14c47a49643389029a2026b4d4fec7ae) for examples.

From what I see [here](http://manpages.ubuntu.com/manpages/trusty/man1/notify-send.1.html) I think you should be able to choose either a path or a named icon.

```
       -i, --icon=ICON[,ICON...]
              Specifies an icon filename or stock icon to display.
```

Anyway if you grep the code of this plugin for `$icon` you'll get the impression it's never set, [because it's set by `zstyle`](https://github.com/marzocchi/zsh-notify/blob/master/notify-if-background#L145).

**Comment by adambro** [comment]
Thanks for the feedback. I'm new to ZSH and it's scripting, so I did not know about the `zstyle` thing. Indeed the following sets things for me:
```
zstyle ':notify:*' error-icon dialog-error
zstyle ':notify:*' success-icon dialog-information
```
Thanks again for help! :)

**Comment by marzocchi** [comment]
thank _you_, it's actually good to know it actually works as I don't use linux that much ;)
